Develop
brunolofaro-uade/TPO_P2_LN_grupo_04 pull request #1
Opened 2023-04-28 21:57 UTC by brunolofaro-uade

Nico, Abro este PR para chequear la estructura gral de proyecto y como venimos avanzando.

2023-04-28 22:56 UTC, nicolas-monzon commented on TP/src/main/java/org/classes/dynamic/Queue.java
> +    private Node first;
Acá `Node` se debería definir como `Node<T>`

2023-04-28 22:56 UTC, nicolas-monzon commented on TP/src/main/java/org/classes/dynamic/Queue.java
> +        Node node = new Node(a, null);
Y en cualquier creación de nodo debería ser `new Node<>(...)`

2023-04-28 22:57 UTC, nicolas-monzon commented on TP/src/main/java/org/classes/dynamic/Queue.java
> +        Node node = new Node(a, null);
Esto se llama operador diamante. Cuando haces `new`, es optativo indicar el tipo de dato dentro cuando lo puede deducir por sintaxis.

2023-04-28 22:57 UTC, nicolas-monzon commented on TP/src/main/java/org/classes/dynamic/Stack.java
> +    private Node first;
Ídem lo de `Queue`

2023-04-28 23:00 UTC, nicolas-monzon requested changes
En general todo esta bien. La carpeta `.idea` no se debe commitear, deberías tener un `.gitignore` que haga que no se suba tras cada commit. Ahora, si lo agregas no va a tener efecto porque ya esta pusheado. Para arreglarlo, cerrar el proyecto desde IntelliJ, y luego:
1. Borras todo excepto src y el pom.xml
2. Commiteas los cambios de borrado
3. Commiteas un gitignore al root del proyecto. Generalo con ChatGPT al estilo "gitignore para Java con Maven e IntelliJ".
4. Importa el proyecto desde IntelliJ y comproba que todos los archivos que te generan no son cambios detectados para commitear. Si no detecta nada, lo hiciste bien. Si aparece algo para commitear deciselo a ChatGPT para que te corrija el gitignore

2023-05-01 16:45 UTC, brunolofaro-uade commented on TP/src/main/java/org/classes/dynamic/Queue.java
> +        Node node = new Node(a, null);
Listo! gracias

2023-05-01 16:58 UTC, merged